name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/2-0. Typing_Practice_Help_Tips.json
    - assets/data/2-1. 50 One-letter Words.json
    - assets/data/2-2. 50 Two-letter Words.json
    - assets/data/2-3. 50 Three-letter Words.json
    - assets/data/2-4. 30 One-sentence Practices.json
    - assets/data/2-5. 30 Paragraph Practices.json
    - assets/data/0. Help System on Inactivity.json
    - assets/data/0. On Entering the Main Screen.json
